package com.example.DevBrain.dto;

public enum SearchType {
    GRAPH_COMPLETION,
    RAG_COMPLETION,
    CHUNKS,
    SUMMARIES,
    TEMPORAL,
    FEELING_LUCKY,
    AGENTIC_COMPLETION,
    GRAPH_COMPLETION_COT,
    GRAPH_COMPLETION_CONTEXT_EXTENSION,
    TRIPLET_COMPLETION,
    CHUNKS_LEXICAL,
    CYPHER,
    NATURAL_LANGUAGE
}
